FROM node:20.11.1 AS builder

WORKDIR /app
COPY . .
RUN npm install -g @angular/cli
RUN yarn install
RUN ng build --configuration production 

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/* /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
