

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod_net

  back-app:
    build: ./backend
    container_name: back-app
    ports: 
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    restart: always
    networks:
      - prod_net

  angular-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-app
    ports:
      - '80:80'
    environment:
      - API_URL=${API_URL}
    restart: always
    networks:
      - prod_net


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - prod_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart : always
    ports:
    - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - prod_net



  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration de Prometheus
      - prometheus_data:/prometheus  # Volume persistant pour les données de Prometheus
    networks:
      - prod_net
    depends_on:
    - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "9080:3000" 
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - prod_net

volumes:
  portainer_data:
    driver: local
  mysql-data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local  

networks:
  prod_net:
    driver: bridge
