

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod_net

  back-app:
    build: ./backend
    container_name: back-app
    ports: 
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    restart: always
    networks:
      - prod_net

  angular-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-app
    ports:
      - '80:80'
    environment:
      - API_URL=${API_URL}
    restart: always
    networks:
      - prod_net



volumes:
  mysql-data:
    driver: local

networks:
  prod_net:
    driver: bridge
